Last release before RPi2 support

diff --git a/scripts/etc/init.d/rcS b/scripts/etc/init.d/rcS
--- a/scripts/etc/init.d/rcS
+++ b/scripts/etc/init.d/rcS
@@ -5,7 +5,7 @@ preset=minimal
 packages=
 mirror=http://mirrordirector.raspbian.org/raspbian/
 release=wheezy
-hostname=pi.localhost
+hostname=pi
 rootpw=root
 cdebootstrap_cmdline=
 bootsize=+50M
@@ -18,6 +18,7 @@ ip_nameservers=
 online_config=
 usbroot=
 cmdline="dwc_otg.lpm_enable=0 console=ttyAMA0,115200 kgdboc=ttyAMA0,115200 console=tty1 elevator=deadline"
+rootfstype=ext4
 
 # these shouldn't really be changed unless auto-detection fails
 bootdev=/dev/mmcblk0
@@ -60,15 +61,17 @@ echo
 echo
 echo
 echo "==========================================="
-echo "Raspinimal (wheezy)"
+echo "Raspinimal (Wheezy + Latest Kernel + ex4)"
 echo "==========================================="
-echo "Version 1.0.3 (Latest Kernel)"
-echo "Built on Fri January 17 23:35:44 GMT 2014"
+echo "Version 1.0.4 (Latest Kernel/ex4)"
+echo "Built on Sun March 30 09:49:44 GMT 2014"
 echo "==========================================="
 echo "http://github.com/TheRPi/Raspinimal"
-echo "http://www.iRaspberryPi.pw"
 echo "==========================================="
-echo
+echo "IRC: irc.foxatomic.net"
+echo "Channel: #brodin"
+echo "Port: 6667"
+echo "Website: http://brodin.us"
 echo
 echo
 sleep 10
@@ -87,6 +90,9 @@ cp /boot/bootcode.bin \
     /boot/start.elf \
     /boot/start_x.elf /bootfs/ || fail
 
+# use install kernel in first boot
+cp /boot/kernel_install.img /bootfs/kernel.img || fail
+
 if [ -f /boot/installer-config.txt ]; then
     cp /boot/installer-config.txt /bootfs/installer-config.txt || fail
 fi
@@ -99,7 +105,6 @@ fi
 cp /boot/config.txt /bootfs/config.txt || fail
 cp /boot/defaultconfig.txt /bootfs/defaultconfig.txt
 
-
 umount /boot || fail
 echo "OK"
 
@@ -107,6 +112,27 @@ if [ -e /bootfs/installer-config.txt ]; then
     echo "Reading installer-config.txt..."
     source /bootfs/installer-config.txt
 fi
+
+case "$rootfstype" in
+  "btrfs")
+    kernel_module=true
+    rootfs_mkfs_options=${rootfs_mkfs_options:-'-f'}
+    rootfs_install_mount_options=${rootfs_install_mount_options:-'noatime'}
+    rootfs_mount_options=${rootfs_mount_options:-'noatime'}
+    ;;
+  "ext4")
+    kernel_module=false
+    rootfs_mkfs_options=${rootfs_mkfs_options:-''}
+    rootfs_install_mount_options=${rootfs_install_mount_options:-'noatime,data=writeback,nobarrier,noinit_itable'}
+    rootfs_mount_options=${rootfs_mount_options:-'errors=remount-ro,noatime'}
+    ;;
+  "f2fs")
+    kernel_module=true
+    rootfs_mkfs_options=${rootfs_mkfs_options:-''}
+    rootfs_install_mount_options=${rootfs_install_mount_options:-'noatime'}
+    rootfs_mount_options=${rootfs_mount_options:-'errors=remount-ro,noatime'}
+    ;;
+esac
 
 echo
 echo "Network configuration:"
@@ -193,15 +219,14 @@ if [ "$cdebootstrap_cmdline" = "" ]; then
             cdebootstrap_cmdline="$cdebootstrap_cmdline,rsyslog,cron,nano,vim-tiny,ca-certificates,man-db,less,iptables"
             preset=server
             ;;
-
     esac
 
     # add extra packages
-    if [ "$packages" != "" ]; then
+    if [ "$packages" != "isc-dhcp-client,openssh-server,apt-utils" ]; then
         if [ "$preset" = "base" ]; then
             cdebootstrap_cmdline="$cdebootstrap_cmdline --include=$packages"
         else
-            cdebootstrap_cmdline="$cdebootstrap_cmdline,isc-dhcp-client,ifupdown,net-tools,openssh-server,openntpd,fake-hwclock,$packages"
+            cdebootstrap_cmdline="$cdebootstrap_cmdline,$packages"
         fi
     fi
 
@@ -236,6 +261,10 @@ echo "  cmdline = $cmdline"
 echo "  usbroot = $usbroot"
 echo "  rootdev = $rootdev"
 echo "  rootpartition = $rootpartition"
+echo "  rootfstype = $rootfstype"
+echo "  rootfs_mkfs_options = $rootfs_mkfs_options"
+echo "  rootfs_install_mount_options = $rootfs_install_mount_options"
+echo "  rootfs_mount_options = $rootfs_mount_options"
 echo
 
 if [ "$timeserver" != "" ]; then
@@ -318,12 +347,18 @@ echo -n "Initializing /boot as vfat... "
 mkfs.vfat $bootpartition &>/dev/null || fail
 echo "OK"
 
-echo -n "Initializing / as ext4... "
-mkfs.ext4 $rootpartition &>/dev/null || fail
+if [ "$kernel_module" == true ] ; then
+  echo -n "Loading $rootfstype module..."
+  modprobe $rootfstype &> /dev/null || fail
+  echo "OK"
+fi
+
+echo -n "Initializing / as $rootfstype... "
+mkfs.$rootfstype $rootfs_mkfs_options $rootpartition &>/dev/null || fail
 echo "OK"
 
 echo -n "Mounting new filesystems... "
-mount $rootpartition /rootfs -o noatime,data=writeback,nobarrier,noinit_itable || fail
+mount $rootpartition /rootfs -o $rootfs_install_mount_options || fail
 mkdir /rootfs/boot || fail
 mount $bootpartition /rootfs/boot || fail
 echo "OK"
@@ -333,8 +368,20 @@ cp /bootfs/* /rootfs/boot || fail
 sync
 echo "OK"
 
+if [ "$rootfstype" = "f2fs" ] ; then
+  mkdir -p /rootfs/etc/initramfs-tools
+  echo "f2fs" >> /rootfs/etc/initramfs-tools/modules
+elif [ "$rootfstype" = "btrfs" ] ; then
+  mkdir -p /rootfs/etc/initramfs-tools
+  echo "btrfs" >> /rootfs/etc/initramfs-tools/modules
+fi
+
 echo "Starting install process..."
 cdebootstrap-static --arch=armhf --allow-unauthenticated $cdebootstrap_cmdline $release /rootfs $mirror || fail
+
+# install latest kernel in /boot
+#echo -n "Install new kernel..."
+#cp -a /rootfs/vmlinuz /rootfs/boot/kernel.img
 
 # allow root login
 echo -n "Configuring installed system... "
@@ -342,7 +389,7 @@ echo -n root:$rootpw | chroot /rootfs /usr/sbin/chpasswd || fail
 
 # default mounts
 echo "$bootpartition /boot vfat defaults 0 0" > /rootfs/etc/fstab || fail
-echo "$rootpartition / ext4 errors=remount-ro,noatime 0 0" >> /rootfs/etc/fstab || fail
+echo "$rootpartition / $rootfstype $rootfs_mount_options 0 0" >> /rootfs/etc/fstab || fail
 
 # use ram tmpfs by default
 echo "RAMTMP=yes" >> /rootfs/etc/default/tmpfs 
@@ -372,13 +419,6 @@ fi
 # there is no hw clock on rpi
 echo "HWCLOCKACCESS=no" >> /rootfs/etc/default/hwclock || fail
 
-# allow ntpd to set time on boot
-if [ -e /rootfs/etc/default/openntpd ]; then
-    echo "DAEMON_OPTS=\"-f /etc/openntpd/ntpd.conf -s\"" > /rootfs/etc/default/openntpd || fail
-fi
-
-echo "OK"
-
 echo "Configuring bootloader to start the installed system..."
 mv /rootfs/boot/config.txt /rootfs/boot/config-reinstall.txt
 cp /rootfs/boot/defaultconfig.txt /rootfs/boot/config.txt
@@ -398,6 +438,7 @@ echo "#deb-src http://archive.raspbian.org/raspbian jessie main contrib firmware
 wget -q -O - http://archive.raspberrypi.org/debian/raspberrypi.gpg.key | chroot /rootfs /usr/bin/apt-key add - &>/dev/null
 echo "OK"
 
+
 # add reasonable default modules, works only after kernel is properly installed
 echo "snd-bcm2835" >> /rootfs/etc/modules
 echo "ipv6" >> /rootfs/etc/modules
@@ -405,7 +446,7 @@ echo "bcm2708_wdog" >> /rootfs/etc/modules
 
 # default cmdline.txt
 echo "Creating default cmdline.txt..."
-echo "$cmdline root=$rootpartition rootfstype=ext4 rootwait" > /rootfs/boot/cmdline.txt 
+echo "$cmdline root=$rootpartition rootfstype=$rootfstype rootwait" > /rootfs/boot/cmdline.txt
 
 # run post install script if exists
 if [ -e /bootfs/post-install.txt ]; then
